apiVersion: v1
kind: Secret
metadata:
  name: soa-secrets
  namespace: soa-hotel
type: Opaque
stringData:
  db-password: "secret"
  rabbitmq-password: "secret"
  rabbitmq-url: "amqp://admin:secret@rabbitmq:5672"
  mongo-url: "mongodb://mongo1:27017/service1db"
  postgres1-url: "jdbc:postgresql://postgres1:5432/authdb"
  postgres2-url: "postgresql+asyncpg://postgres:secret@postgres2:5432/service3db"