spring.application.name=service1
server.port=3001
spring.datasource.url=jdbc:postgresql://postgres1:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=secret

# URL du service2 (Node.js)
service2.url=http://service2:8081
